services:
  # use gradle as init container to download pg jar for hive metastore
  # https://stackoverflow.com/a/32402694/11722440
  metastore-init-jars-download:
    image: gradle:8
    restart: on-failure
    volumes:
      - hive-jars:/jars
      - gradle-cache:/home/gradle/.gradle/
      - type: bind  # 使用 bind 挂载单个文件到容器中
        source: ${PWD}/config/hive/build.gradle
        target: /home/gradle/build.gradle
    command: |
      bash -c '
      gradle download
      '

  trino-init-jars-download:
    image: gradle:8
    restart: on-failure
    volumes:
      - trino-jars:/jars
      - gradle-cache:/home/gradle/.gradle/
      - type: bind  # 使用 bind 挂载单个文件到容器中
        source: ${PWD}/config/trino/build.gradle
        target: /home/gradle/build.gradle
    command: |
      bash -c '
      gradle download
      '

  # merge hive jars
  # https://stackoverflow.com/a/32402694/11722440
  metastore-init-jars-merge:
    image: apache/hive:4.0.0-beta-1
    restart: on-failure
    user: root
    volumes:
      - hive-jars:/jars:rw
    entrypoint: |
      bash -c '
      cp -R /opt/hive/lib/* /jars
      '

  # due to mount volume will override the original content, so we need to copy the jars to another volume
  # and then mount the volume to trino container
  trino-init-jars-merge:
    image: trinodb/trino:452
    restart: on-failure
    user: root
    volumes:
      - type: volume
        source: trino-jars
        target: /jars
    entrypoint: |
      bash -c '
      cp /usr/lib/trino/plugin/iceberg/* /jars
      '

  init-certs:
    image: rockylinux/rockylinux:9
    restart: on-failure
    volumes:
      - type: bind
        source: ${PWD}/scripts/init-certs.sh
        target: /init-certs.sh
      - certs:/certs
    entrypoint: |
      bash -c '
      cd /certs
      /init-certs.sh
      '

  # minio s3 init
  minio-init:
    image: quay.io/minio/minio:RELEASE.2023-08-16T20-17-30Z
    restart: on-failure
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${PWD}/scripts/minio-init.sh
        target: /minio-init.sh
    entrypoint: |
      bash -c '
      /minio-init.sh
      '

volumes:
  hive-jars:
  trino-jars:
  certs:
  gradle-cache:
