x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0
  env_file:
      - .env

services:
  # trino server
  trino:
    image: trinodb/trino:424
    user: root
    hostname: trino
    domainname: trino.example.com
    << : *default-config
    environment:
      AWS_ACCESS_KEY_ID: ${LAKEHOUSE_USER}
      AWS_SECRET_ACCESS_KEY: ${LAKEHOUSE_PASSWORD}
      AWS_S3_ENDPOINT: http://minio:9000
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ${PWD}/config/trino/catalog:/etc/trino/catalog
      - trino-data:/lakehouse/data
      - trino-iceberg-jars:/usr/lib/trino/plugin/iceberg

volumes:
  trino-data:
  trino-iceberg-jars:
