version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0
  env_file:
      - .env

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-08-16T20-17-30Z
    << : *default-config
    command: server /data --console-address ":9001"
    hostname: minio
    # ports:
    #   - 127.0.0.1:9000:9000
    #   - 127.0.0.1:9001:9001
    volumes:
      - lakehouse-minio:/data
    # environment:
      # MINIO_ROOT_USER: minioadmin
      # MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  lakehouse-minio: