version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:
  mongo-rs-1:
    image: mongo:7
    << : *default-config
    environment:
      MONGO_INITDB_DATABASE: test
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
    #   - ${PWD}/scripts:/docker-entrypoint-initdb.d/
      - /data/docker/mongodb/data:/data/db
    # command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]

networks:
  default:
    name: db
    external: true
