x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:
  mongo-1:
    image: quay.io/mongodb/mongodb-community-server:7.0.1-ubi9
    << : *default-config
    environment:
      MONGO_INITDB_DATABASE: test
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - /data/docker/mongodb/data:/data/db

networks:
  default:
    name: db
    external: true
