x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:
  db:
    image: registry.access.redhat.com/rhel9/postgresql-16:1-25.1724037700
    << : *default-config
    env_file: ./.env
    volumes:
      - /data/docker/pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - db

networks:
  db:
    external: true
